services:
  ######################################################
  # R Book
  ######################################################
  r-book:
    image: tidylab/book:4.0.4
    build:
      context: ./
      dockerfile: ./.dev/docker/r-book/Dockerfile
    entrypoint: '/bin/bash'
    container_name: r_book
    restart: "no"
  ######################################################
  # R Testing
  ######################################################
  r-test:
    image: publications/mastering-r-projects
    build:
      context: ./
      dockerfile: ./.dev/docker/r-test/Dockerfile
    entrypoint: '/bin/bash'
    container_name: r_test
    restart: "no"
  ######################################################
version: "3.8"
networks:
  default:
    name: r-package
