services:
  ######################################################
  # R Testing
  ######################################################
  r-test:
    image: publications/mastering-r-projects
    build:
      context: ./
      dockerfile: ./.dev/docker/r-test/Dockerfile
    entrypoint: '/bin/bash'
    container_name: r_test
    restart: "no"
  ######################################################
version: "3.3"
networks:
  default:
    name: r-package
